# Generated by Django 5.0.3 on 2024-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
