# Generated by Django 5.0.3 on 2024-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework_2', '0002_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='Homework_4'),
        ),
    ]
